# Development Docker Compose for Sitemap Scraper Application
# Optimized for ARM64 with hot reloading and development features

version: '3.8'

services:
  # Firecrawl Backend Service (Development)
  firecrawl-backend-dev:
    build:
      context: ./firecrawl-service
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    container_name: firecrawl-backend-dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=dev-jwt-secret-not-for-production
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:$FRONTEND_PORT
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
      - CACHE_TTL_SECONDS=300
      - PLAYWRIGHT_TIMEOUT=30000
      - PLAYWRIGHT_MAX_CONCURRENT=2
      - DEBUG=firecrawl:*
    ports:
      - "$BACKEND_PORT:3001"
      - "9229:9229"  # Node.js debugger port
    volumes:
      - ./firecrawl-service/src:/app/src:ro
      - ./firecrawl-service/package.json:/app/package.json:ro
      - firecrawl_dev_logs:/app/logs
      - firecrawl_dev_temp:/app/temp
    networks:
      - sitemap-dev-network
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Synthora Analytics Frontend (Development)
  synthora-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    container_name: synthora-frontend-dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:$BACKEND_PORT
      - VITE_APP_NAME=Synthora Analytics (Dev)
      - VITE_DEV_MODE=true
      - HMR_HOST=localhost
      - HMR_PORT=5173
    ports:
      - "$FRONTEND_PORT:5173"
      - "5173:5173"  # Vite HMR port
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./package.json:/app/package.json:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./index.html:/app/index.html:ro
    depends_on:
      - firecrawl-backend-dev
    networks:
      - sitemap-dev-network
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Redis for development caching
  redis-dev:
    image: redis:7-alpine
    container_name: sitemap-redis-dev
    platform: linux/arm64
    ports:
      - "$REDIS_PORT:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - sitemap-dev-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru

  # Development tools container
  dev-tools:
    image: node:20-alpine
    container_name: sitemap-dev-tools
    platform: linux/arm64
    working_dir: /workspace
    volumes:
      - .:/workspace
      - dev_tools_cache:/root/.npm
    networks:
      - sitemap-dev-network
    profiles:
      - tools
    command: ["sleep", "infinity"]

# Networks
networks:
  sitemap-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

# Volumes
volumes:
  firecrawl_dev_logs:
    driver: local
  firecrawl_dev_temp:
    driver: local
  redis_dev_data:
    driver: local
  dev_tools_cache:
    driver: local